// Don't clash with actual Carbon names to allow linking for
// PowerPC systems that have a genuine Carbon implementation

#define AddResource				Pomme_AddResource
#define BlockMove				Pomme_BlockMove
#define BlockMoveData			Pomme_BlockMoveData
#define ChangedResource			Pomme_ChangedResource
#define CloseResFile			Pomme_CloseResFile
#define Count1Resources			Pomme_Count1Resources
#define Count1Types				Pomme_Count1Types
#define CurResFile				Pomme_CurResFile
#define DetachResource			Pomme_DetachResource
#define DirCreate				Pomme_DirCreate
#define DisposeHandle			Pomme_DisposeHandle
#define DisposePtr				Pomme_DisposePtr
#define ExitToShell				Pomme_ExitToShell
#define FSClose					Pomme_FSClose
#define FSMakeFSSpec			Pomme_FSMakeFSSpec
#define FSRead					Pomme_FSRead
#define FSWrite					Pomme_FSWrite
#define FSpCreate				Pomme_FSpCreate
#define FSpDelete				Pomme_FSpDelete
#define FSpOpenDF				Pomme_FSpOpenDF
#define FSpOpenRF				Pomme_FSpOpenRF
#define FSpOpenResFile			Pomme_FSpOpenResFile
#define FindFolder				Pomme_FindFolder
#define FlushEvents				Pomme_FlushEvents
#define Get1IndResource			Pomme_Get1IndResource
#define Get1IndType				Pomme_Get1IndType
#define GetDateTime				Pomme_GetDateTime
#define GetDefaultOutputVolume	Pomme_GetDefaultOutputVolume
#define GetEOF					Pomme_GetEOF
#define GetFPos					Pomme_GetFPos
#define GetHandleSize			Pomme_GetHandleSize
#define GetPtrSize				Pomme_GetPtrSize
#define GetResInfo				Pomme_GetResInfo
#define GetResource				Pomme_GetResource
#define GetResourceSizeOnDisk	Pomme_GetResourceSizeOnDisk
#define GetSoundHeaderOffset	Pomme_GetSoundHeaderOffset
#define HideCursor				Pomme_HideCursor
#define InitCursor				Pomme_InitCursor
#define Microseconds			Pomme_Microseconds
#define NewHandle				Pomme_NewHandle
#define NewHandleClear			Pomme_NewHandleClear
#define NewPtr					Pomme_NewPtr
#define NewPtrClear				Pomme_NewPtrClear
#define NumToString				Pomme_NumToString
#define PtrToHand				Pomme_PtrToHand
#define ReleaseResource			Pomme_ReleaseResource
#define RemoveResource			Pomme_RemoveResource
#define ResError				Pomme_ResError
#define ResolveAlias			Pomme_ResolveAlias
#define SetDefaultOutputVolume	Pomme_SetDefaultOutputVolume
#define SetEOF					Pomme_SetEOF
#define SetFPos					Pomme_SetFPos
#define SetHandleSize			Pomme_SetHandleSize
#define ShowCursor				Pomme_ShowCursor
#define SndChannelStatus		Pomme_SndChannelStatus
#define SndDisposeChannel		Pomme_SndDisposeChannel
#define SndDoCommand			Pomme_SndDoCommand
#define SndDoImmediate			Pomme_SndDoImmediate
#define SndNewChannel			Pomme_SndNewChannel
#define SndSoundManagerVersion	Pomme_SndSoundManagerVersion
#define SysBeep					Pomme_SysBeep
#define TempNewHandle			Pomme_TempNewHandle
#define TickCount				Pomme_TickCount
#define UseResFile				Pomme_UseResFile
#define WriteResource			Pomme_WriteResource
